export { ChatsPage } from './chats'
export { ErrorPage } from './error'
export { LoginPage } from './login'
export { ProfilePage, ChangeProfileDataPage, ChangeProfilePasswordPage } from './profile'
export { RegistrationPage } from './registration'